### ISSUE TITLE
[BUG] [WeaponCoreTurretScript-1.16.2] Some edge cases crash the script.

### ISSUE THREAD

**Issue by SilicDev** [SilicDev/WeaponCoreScripts#2]
**Which script is this issue related to (including script version if accessible)**
WeaponCoreTurretScript-1.16.2 (latest version)

**Describe the bug**
The script crashes when an enemy is detected.

**To Reproduce**
1. The inspected Turret didn't seem to be special to me, so this might affect all configs.
2. No direct copy but [ApiBackend](https://github.com/sstixrud/WeaponCore/blob/master/Data/Scripts/CoreSystems/Api/ApiBackend.cs).IsTargetAligned() gets an Object reference not set to an instance error.
3. Error happened with [Halo UNSC Ship Weapons (WeaponCore)](https://steamcommunity.com/sharedfiles/filedetails/?id=2286546132)

**Expected behavior**
The turret should aim at the enemy.

**Screenshots**
None

**Additional context**
Reported on Steam

https://steamcommunity.com/sharedfiles/filedetails/?id=2657836581

**Comment by mkaito** [comment]
Here's some random data I gathered while debugging:

The only weapon I was able to get any turrets to fire along with was a Spicy Meatball, from MA Weaponcore Weapons. Anything else would crash the script. But it also crashed with a meatball when I put it in manual targetting and told it to shoot something from a cockpit.

Worth noting that the mere presence of (replaced) vanilla interior turrets on the grid would result in a crash when any WC turret acquired a target.

Hope that helps narrow it down a bit.

**Comment by SilicDev** [comment]
Thanks mkaito. While your input didn't directly help with this issue, I noticed another minor bug during testing with different turrets. In the end it seems that WC used to validate the EntityId before using it allowing a flawed assumption of `MyDetectedEntityInfo?` to work.

As a potential fix has been pushed onto the workshop the issue will be marked as closed in 7 days unless the issue is encountered again.

**Comment by mkaito** [comment]
Yep, seems to fix the crash.
